### ISSUE TITLE
No results found for wakatime in Creative Cloud

### ISSUE THREAD

**Issue by badasukerubin** [wakatime/adobe-xd-wakatime#1]
Awesome package with WakaTime. I've been using it for some years now and I had been able to integrate it with all my IDEs except Adobe XD. 
There seems to be no plugin for this in Creative Cloud. 
Attached is a screenshot.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/20546078/157000937-10319c9c-a62d-457c-bcd9-33f7d6837415.png">

**Comment by Manfrinmm** [comment]
I have the same problem

**Comment by pgm-emmavanderhaeghen** [comment]
I have the same issue.

**Comment by VinnieVH** [comment]
Same issue here

**Comment by gandarez** [comment]
@alanhamlett

**Comment by alanhamlett** [comment]
We received these rejection reasons in an email from Adobe:

> 1. Adobe Muse and Prelude are no longer supported products. Please remove them from the list of compatible products.
> 2. Upon installing the .zxp file, a zipped folder gets generated in the Downloads folder &quot;adobe-xd-wakatime-master.zip&quot;, which only contains the files with coding information of your plugin.

I've re-submitted the app to the marketplace for approval, but I wasn't sure how to fix these two issues since the extension doesn't list Muse nor Prelude anywhere as supported.

**Comment by alanhamlett** [comment]
Submitting now using [Adobe Developer Console](https://developer.adobe.com/console) instead of the legacy partner exchange, so hopefully it works this time!

**Comment by funkysoul** [comment]
bump?

**Comment by alanhamlett** [comment]
I received a response from Adobe on June 27, 2022:

> Your public profile website uses Adobe Branding assets but you have not been approved by the Adobe Branding team to do so. To get proper authorization to use these assets, please contact the Brand or Marketing team for the appropriate approvals. The email is: [CCDeveloperMarketing@adobe.com](mailto:CCDeveloperMarketing@adobe.com)

I've emailed that address twice, most recently on July 1st, and have not received any response. If anyone knows someone inside Adobe we're currently blocked on publishing the extension because of this.

**Comment by allefrodrigo** [comment]
Any chance to install the plugin in manually or in offline mode?

**Comment by alanhamlett** [comment]
> Any chance to install the plugin in manually or in offline mode?

You can manually install the plugin by downloading and double clicking on this file: [adobe-xd-wakatime-v1.0.0.xdx](https://github.com/wakatime/adobe-xd-wakatime/releases/download/v1.0.0/adobe-xd-wakatime-v1.0.0.xdx)

**Comment by alanhamlett** [comment]
WakaTime is available in Creative Cloud now.
